// sanity/fetch.ts
import { client } from "./client";
import { groq } from "next-sanity";
import { Prospect, NudgeTemplate } from "@/types/sanity.types"; // Generated by TypeGen



// Fetch only active templates
export async function fetchActiveNudgeTemplates(): Promise<NudgeTemplate[]> {
    const query = groq`
        *[_type == "nudgeTemplate" && isActive == true] | order(category asc) {
            _id,
            title,
            category,
            body,
            isActive
        }
    `;
    return await client.fetch(query);
}
// Query definition
export const PROSPECTS_QUERY = groq`
  *[_type == "prospect"] | order(_createdAt desc) {
    _id,
    name,
    phone,
    currentStep,
    crmData[]{ // Use array syntax [] without dereference ->
        key,
        value
    },
      lastInteraction
  }
`;

// Fetch function with Caching
export async function fetchProspects(): Promise<Prospect[]> {
    return await client.fetch(
        PROSPECTS_QUERY,
        {},
        {
            next: { revalidate: 60 }, // Revalidate every minute

        }
    );
}