// sanity/fetch.ts
import { client } from "./client";
import { groq } from "next-sanity";
import { Prospect } from "@/types/sanity.types"; // Generated by TypeGen

// Query definition
export const PROSPECTS_QUERY = groq`
  *[_type == "prospect"] | order(_createdAt desc) {
    _id,
    name,
    phone,
    currentStep,
    crmData[]->{key, value},
    lastInteraction
  }
`;

// Fetch function with Caching
export async function fetchProspects(): Promise<Prospect[]> {
    return await client.fetch(
        PROSPECTS_QUERY,
        {},
        {
            next: { revalidate: 60 }, // Revalidate every minute

        }
    );
}