// sanity/fetch.ts
import { client } from "./client";
import { groq } from "next-sanity";
import { Prospect, NudgeTemplate } from "@/types/sanity.types"; // Generated by TypeGen



// Fetch only active templates
export async function fetchActiveNudgeTemplates(): Promise<NudgeTemplate[]> {
    try {
        const templates = await client.fetch(groq`
            *[_type == "nudgeTemplate" && isActive == true] | order(category asc) {
                _id, title, category, messageBody, isActive
            }
        `);
        console.log("Templates fetched:", templates); // Check your terminal/browser console
        return templates || [];
    } catch (error) {
        console.error("Sanity Fetch Error Details:", error);
        return []; // Return empty so the UI doesn't crash
    }
}
// Query definition
export const PROSPECTS_QUERY = groq`
  *[_type == "prospect"] | order(_createdAt desc) {
    _id,
    telegramChatId,
    username,
    name,
    phone,
    currentStep,
    crmData[]{ // Use array syntax [] without dereference ->
        key,
        value
    },
      lastInteraction
  }
`;

// Fetch function with Caching
export async function fetchProspects(): Promise<Prospect[]> {
    return await client.fetch(
        PROSPECTS_QUERY,
        {},
        {
            next: { revalidate: 60 }, // Revalidate every minute

        }
    );
}